version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "23:59"
    open-pull-requests-limit: 10
    target-branch: "dev"
    labels:
    - dependabot
